titre("THEMES SELECTION");
titre("NUMBER OF QUESTIONS");
titre("QUESTION N°");
titre("Note : ");
titre("THEMES SELECTED");
titre("NUMBER OF QUESTIONS SELECTED");
titre("YOUR SCORE");
titre("ELAPSED TIME TO DO THE EXERCICE");
titre("COMMENTS");
bouton("START");
bouton("QUIT");
bouton("CHECK");
bouton("NEXT QUESTION");
bouton("I DON'T KNOW");
bouton("STOP");
bouton("HOME PAGE");
bouton("SAVE THE SCORE");
bouton("HELP");
fenetre("Please select at least one theme.");
fenetre("Please select a number of questions.");
fenetre("Not enough available questions for quiz choice !");
fenetre("Give your name please.");
fenetre("Answer the question please.");
fenetre("You did not fill in all the required fields. Are you sure you want to continue?");
fenetre("You did not answer all the questions. Are you sure you want to quit ?");
mot("All themes");
mot("questions");
mot("Name and first name : ");
mot("Warning Dyris");
mot("A new score is saved on the server");
score("Name and first name");
score("Themes selection");
score("Number of questions");
score("Elapsed Time");
score("Score");
score("QUIT");
score("ERASE THE RECORDINGS");
score("Your score is saved.");
