titre("SELECTION DES THEMES");
titre("NOMBRE DE QUESTIONS");
titre("QUESTION N°");
titre("Note : ");
titre("THEME(S) SELECTIONNE(S)");
titre("NOMBRE DE QUESTIONS CHOISI");
titre("VOTRE NOTE");
titre("TEMPS MIS POUR REPONDRE AUX QUESTIONS");
titre("APPRECIATION");
bouton("COMMENCER");
bouton("QUITTER");
bouton("VALIDER");
bouton("SUIVANT");
bouton("JE NE SAIS PAS");
bouton("ARRETER");
bouton("ACCUEIL");
bouton("ENREGISTRER LE SCORE");
bouton("AIDE");
fenetre("Veuillez sélectionner un thème, s'il vous plaît.");
fenetre("Veuillez sélectionner un nombre d'exercices, s'il vous plaît.");
fenetre("Pas assez de questions disponibles avec ce choix d'options !");
fenetre("Inscrivez, s'il vous plait, votre identifiant pour commencer l'évaluation.");
fenetre("Vous n'avez pas répondu à la question!");
fenetre("Vous n'avez pas répondu complètement à la question. Etes-vous sûr de vouloir continuer?");
fenetre("Vous n'avez pas terminé ! Etes-vous sûr de vouloir quitter ?");
mot("Tous les thèmes");
mot("questions");
mot("Identifiant : ");
mot("Avertissement Dyris");
mot("Un nouveau bilan est sauvegardé sur le serveur.");
score("Identifiant");
score("Thème(s) choisi(s)");
score("Nombre de questions");
score("Temps");
score("Note");
score("QUITTER");
score("EFFACER LES SCORES");
score("Votre score a bien été enregistré.");
